-- Drop old tables (safe re-run)
DROP TABLE IF EXISTS LOAN;
DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS MEMBER;

-- MEMBER table
CREATE TABLE MEMBER (
                        ID               INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
                        NAME             VARCHAR(120)        NOT NULL,
                        EMAIL            VARCHAR(160)        NOT NULL UNIQUE,
                        MEMBERSHIP_DATE  DATE                NOT NULL
);

-- BOOK table
CREATE TABLE BOOK (
                      ID              INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
                      TITLE           VARCHAR(200)        NOT NULL,
                      AUTHOR          VARCHAR(160)        NOT NULL,
                      ISBN            VARCHAR(20)         NOT NULL UNIQUE,
                      PUBLISHED_YEAR  INTEGER,
                      CONSTRAINT CHK_BOOK_YEAR CHECK (PUBLISHED_YEAR IS NULL OR (PUBLISHED_YEAR BETWEEN 1400 AND 2100))
);

-- LOAN table
CREATE TABLE LOAN (
                      ID          INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY,
                      BOOK_ID     INTEGER NOT NULL,
                      MEMBER_ID   INTEGER NOT NULL,
                      LOAN_DATE   DATE    NOT NULL,
                      RETURN_DATE DATE,
                      CONSTRAINT FK_LOAN_BOOK   FOREIGN KEY (BOOK_ID)   REFERENCES BOOK(ID)   ON DELETE RESTRICT,
                      CONSTRAINT FK_LOAN_MEMBER FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(ID) ON DELETE RESTRICT,
                      CONSTRAINT CHK_DATES CHECK (RETURN_DATE IS NULL OR RETURN_DATE >= LOAN_DATE)
);
